# fly.toml app configuration file generated for dab-back on 2023-07-18T02:48:22-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dab-back"
primary_region = "gru"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
