name: Angular Practices Validation

on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: ESLint check
      run: npm run lint
      working-directory: ./frontend
    
  lint-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install pylint
      
      - name: Pylint check
        run: pylink */*.py
        working-directory: ./backend
