name: Angular Practices Validation

on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: npm install
      working-directory: ./app

    - name: ESLint check
      run: npm run lint
      working-directory: ./frontend