name: Testes

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  testes-unitarios-frontend:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Run tests with code coverage
      run: ng test --code-coverage
      working-directory: ./frontend

    - name: Install dependencies
      run: npm ci

    - name: Run tests and generate coverage
      run: ng test --code-coverage

    #- name: Upload coverage to Code Climate
    #   run: npm install -g codeclimate-test-reporter && codeclimate-test-reporter < ./frontend/coverage/index.html
    #   env:
    #     CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}