name: Testes

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  testes-unitarios-frontend:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Install Angular CLI
      run: npm install -g @angular/cli
      working-directory: ./frontend
    
    - name: Set up Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=:99

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Wait for Xvfb to start
      run: sleep 3

    # Run Unit Tests
    - name: Unit Tests
      run: |
          cd frontend
          ng test
