name: Testes de Unidade - Frontend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Run tests
      run: ng test