name: Testes de Unidade - Frontend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  unit-tests-frontend:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Install dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Run tests
      run: ng test